name: Index doc on tag

on:
  push:
    tags:
      - v*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  index-doc:
    name: Index doc
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Doc indexing webhook for tag
        id: trigger-index
        run: |
          TAG=${GITHUB_REF#refs/*/}
          curl -X POST -H "Content-Type: application/json" -d "{\"tag\": \"$TAG\"}" https://us.kestra.cloud/api/v1/kestra-tech/executions/webhook/product/doc-to-storage/${{ secrets.DOC_INDEXING_WEBHOOK }}